package org.homepoker.domain.user;

import lombok.Value;

/**
 * The domain object represents a request to change a user's password.
 *
 * @author tyler.vangorder
 */
@Value
public class UserPasswordChangeRequest {

  /**
   * This is the existing user's ID
   */
  String loginId;

  /**
   * The user challenge is either the user's existing password or a time-sensitive code generated by the server and sent to the user's email account.
   */
  String userChallenge;

  /**
   * The new password.
   */
  String newPassword;
}
